### ISSUE TITLE
Image field not set returns empty object, not null?

### ISSUE THREAD

**Issue by cloakedninjas** [prismicio-community/php-kit#154]
Some fields when not set return `null` others, namely `Image`, return empty objects. Is there a reason for this ?

**Comment by c0nst4ntin** [comment]
@cloakedninjas Could you please provide me with a bit more information on this topic? I would love to clear this up and help you out

I recently started to support Prismic in maintaining the PHP Kit and would like to resolve this old issue 🙂

**Comment by c0nst4ntin** [comment]
I will proceed to close this Issue. If anybody else has run's into the same problem feel free to re-open the issue and provide me with some more detailed information.

**Comment by c0nst4ntin** [comment]
I will proceed to close this Issue. If anybody else has run's into the same problem feel free to re-open the issue and provide me with some more detailed information.
