### ISSUE TITLE
Prismic::SearchForm url parameters are not correctly separated 

### ISSUE THREAD

**Issue by damyanovg** [prismicio-community/php-kit#157]
https://github.com/prismicio/php-kit/blob/5670c79a639c09b96ad9460592713fad3a7f777d/src/Prismic/SearchForm.php#L265

Example options:
`['pageSize' => 2, 'page' => 2]` they are not separated correctly and the reason the response is incorrect.

With '**?**' as a separator the url looks like this:
`...?page=1&pageSize=100&...`

Once the question mark is changed to '**&**' the parameters are correctly separated:
`...&page=1&pageSize=100&...`

**Comment by c0nst4ntin** [comment]
@damyanovg Could you maybe provide me with a little code example of where this problem appeared to you? I am currently trying to go through all the Issues and PRs on this project to attempt to get things back on track.

**Comment by c0nst4ntin** [comment]
I'll Look into this a bit more tomorrow. But that was exactly the problem I was seeing as well

**Comment by c0nst4ntin** [comment]
Whilst there seems to be no automated test for this, it appears to be fixed: https://github.com/prismicio-community/php-kit/blob/master/src/Prismic/Utils.php#L10

Should I try to add a test for this? Or should we just close this issue?

**Comment by c0nst4ntin** [comment]
I will proceed to mark this as closed for now. If anybody runs into this problem again, please re-open it or start a new issue.
