### ISSUE TITLE
Deprecate preview resolver

### ISSUE THREAD

**Issue by phillysnow** [prismicio-community/php-kit#169]
Can we create a preview token parsing function that doesn't use the unreliable mainDocument?

Like we now do in the javascript kit:
https://github.com/prismicio/prismic-javascript/blob/36670cff4e687d04018c3cffe3ccfb44ad8b2c90/src/client.ts#L73

**Comment by PaulinaVPG** [comment]
Here's a related forum thread: https://community.prismic.io/t/bug-preview-only-works-half-the-time/1232/4

**Comment by c0nst4ntin** [comment]
Since there was no further reactions or messages in this issue I will assume that this is no longer a pain point and proceed to close this issue. If you want to further elaborate the problem or contribute some changes feel free to re-open the issue.

**Comment by c0nst4ntin** [comment]
Since there was no further reactions or messages in this issue I will assume that this is no longer a pain point and proceed to close this issue. If you want to further elaborate the problem or contribute some changes feel free to re-open the issue
