### ISSUE TITLE
Upgrade to Guzzle 7.x

### ISSUE THREAD

**Issue by robindrost** [prismicio-community/php-kit#170]
Hello,

Is it possible to support Guzzle 7.x? It was released in June. Currently new Laravel applications are set to Guzzle 7.x in the composer.json wich results in not being able to install this package.

The current work around is to downgrade Guzzle, but I rather see it gets supported here :)!

**Comment by markwalet** [comment]
Is there any update on when this is coming?

**Comment by goppi0** [comment]
Would be nice to get some feedback from Prismic...

**Comment by gsteel** [comment]
I've personally given up with this library and [written this](https://github.com/netglue/prismic-client) - it's opinionated, but I actively maintain it. It uses PSR standards for everything, so you can use whatever http client you like.

**Comment by markwalet** [comment]
Finally someone who just takes over.

It's a shame that a first party package for a paid service is this poorly maintained... thanks for offering an alternative @gsteel

**Comment by goppi0** [comment]
Thanks @gsteel - hopefully Prismic makes use of the helping hand - after all, albeit they don't seem to reply on Github, the same issue was raised on the forum and someone from Prismic responded that they won't maintain the php sdk anymore and want to hand it over to the community to maintain. That was a while ago though and no further attempt was made by them to help their customers. Another package I found is [zumba/prismic-sdk](https://github.com/zumba/prismic-sdk). Haven't compared it with yours, but by the sounds of it, it's not a complete rewrite, but just patched version. Again,  Prismic should support people that want to help out....

**Comment by gsteel** [comment]
Cheers @goppi0 - the api client I've written _is_ a complete rewrite - I [contributed a lot](https://github.com/prismicio/php-kit/graphs/contributors) to this library but it just got less type safe and more out of date - I'm using my home-grown client in a lot of production projects and it's pretty stable. 

I saw the "handing it over to the community" response but no one has announced anything or reached out to anyone that I'm aware of. It's all about the JavaScript now 🙄

**Comment by ahm750** [comment]
Why isn't the PR from @c0nst4ntin merged yet? It's add support for Guzzle 7.

**Comment by c0nst4ntin** [comment]
I can merge the PR myself. I was just waiting to hear back from @gsteel (probably once the Holliday's have passed) to be sure everything ist alright.

Hopefully this will be released shortly 😉

**Comment by ahm750** [comment]
> 

Awesome, thanks!

**Comment by ahm750** [comment]
Hey @c0nst4ntin, hate to be a bugger but wanted to check when the PR would be merged. 

We upgraded our Laravel website recently and the only thing that's broken is our blog which is powered by Prismic.

Thanks!
