### ISSUE TITLE
Problems in deployment with PHP on Digital Ocean

### ISSUE THREAD

**Issue by hamzamalik47** [prismicio-community/php-kit#178]
Hi There, I have created an application for my client, and trying to deploy this project on digital Ocean I followed your Readme.MD but still it's not working for me. it works fine on my localhost but not on the live server.
![Screenshot 2022-02-08 at 1 20 22 AM](https://user-images.githubusercontent.com/84602203/152865434-f1524cba-184d-4415-9bbb-6c941db6e326.png)
this is my folder structure on my digital ocean account.

**Comment by c0nst4ntin** [comment]
Hey @hamzamalik47 did you manage to solve the problem?

If you are still struggling, please provide me with some more information on the problem and I will do my best to help you!

**Comment by c0nst4ntin** [comment]
@hamzamalik47 I will proceed to close this issue due to its age. If you still need any help with this topic, please reach out to me or re-open this issue.
